from typing import NamedTuple
import os

CONNEXT_TRAIN_DATA_FILE_PATH = os.environ['CONNEXT_TRAIN_DATA_FILE_PATH']
CONNEXT_TEXT_LIMIT = os.getenv('CONNEXT_TEXT_LIMIT', 0)
CONNEXT_SPLIT = os.getenv('CONNEXT_SPLIT', 0.8)
STANFORD_LABELS_FILE_PATH = os.environ['STANFORD_LABELS_FILE_PATH']
STANFORD_PHRASES_FILE_PATH = os.environ['STANFORD_PHRASES_FILE_PATH']
STANFORD_TEXT_LIMIT = os.getenv('STANFORD_TEXT_LIMIT', 0)
STANFORD_SPLIT =  os.getenv('STANFORD_SPLIT', 0.8)
IMDB_TEXT_LIMIT =  os.getenv('IMDB_TEXT_LIMIT', 0)
IMDB_SPLIT =  os.getenv('IMDB_SPLIT', 0.8)
REPORT_FILE_PATH = os.environ['REPORT_FILE_PATH']

class SpacyVars(NamedTuple):
  CONNEXT_TRAIN_DATA_FILE_PATH: str = CONNEXT_TRAIN_DATA_FILE_PATH
  CONNEXT_TEXT_LIMIT: int = CONNEXT_TEXT_LIMIT
  CONNEXT_SPLIT: float = CONNEXT_SPLIT
  STANFORD_LABELS_FILE_PATH: str = STANFORD_LABELS_FILE_PATH
  STANFORD_PHRASES_FILE_PATH: str = STANFORD_PHRASES_FILE_PATH
  STANFORD_TEXT_LIMIT: int = STANFORD_TEXT_LIMIT
  STANFORD_SPLIT: float = STANFORD_SPLIT
  IMDB_TEXT_LIMIT: int = IMDB_TEXT_LIMIT
  IMDB_SPLIT: float = IMDB_SPLIT
  REPORT_FILE_PATH: str = REPORT_FILE_PATH